add init php.ini

diff --git a/src/php/install b/src/php/install
--- a/src/php/install
+++ b/src/php/install
@@ -6,21 +6,23 @@ reinstall()
 }
 
 install() {
-    if [[ -z "$TAR_DIR" ]]
-    then
-        TAR_DIR="$ROOT_DIR/storage/tar"
-        mkdir -p $TAR_DIR
-    fi
-     
-    cd "${TAR_DIR}"
-
+    # Checks whether php is installed 
     if [[ -d "$INSTALL_PREFIX/php"  ]]
     then
-        echo "PHP is already installed."
-        exit 0
+        read -p "PHP is already installed. Reinstall now ?"
+        if [[ $REPLY =~ ^[Yy]$ ]]; then
+            . $SRC_DIR/php/clear
+        else
+            exit 0
+        fi
     fi
 
-    local VER_NAME="php-7.2.12.tar.gz"
+    # download directory
+    if [ "$(type -t __make_and_cd_tar_dir)" = "function" ] ; then
+        __make_and_cd_tar_dir
+    fi
+
+    local VER_NAME="php-7.3.0.tar.gz"
 
     if [[ ! -f "$VER_NAME" ]];then 
         wget --no-check-certificate -O "$VER_NAME" http://cn2.php.net/get/"$VER_NAME"/from/this/mirror
@@ -107,7 +109,93 @@ install() {
         exit 1
     fi
 
+    local bin_path="export PATH=/usr/local/php/bin:/usr/local/php/sbin:\$PATH"
+
+    echo "$bin_path" > /etc/profile.d/php.sh 
+    source /etc/profile.d/php.sh 
+
     log_success "PHP install success."
+}
+
+function ini()
+{
+    local php_src_dir="${TAR_DIR}/php-7.3.0"
+    local php_install_dir="$INSTALL_PREFIX/php"
+    local php_fpm_conf_dir="$INSTALL_PREFIX/php/etc/php-fpm.conf"
+
+    /usr/bin/cp -f "${php_src_dir}/php.ini-production" /etc/php.ini
+    /usr/bin/cp -f "${php_src_dir}/sapi/fpm/init.d.php-fpm.in" /etc/rc.d/init.d/php-fpm
+
+    if [ ! -f /etc/php.ini ];then
+        log_error "Not found ${php_src_dir}/php.ini-production" 
+        exit 1
+    fi 
+    
+    # init php.ini
+    sed -i \
+    "s@^;date.timezone.*@date.timezone = Asia/Shanghai@; \
+     s@^display_errors.*@display_errors = On@; \
+     s@^display_startup_errors.*@display_startup_errors = On@; \
+     s@^post_max_size.*@post_max_size = 64M@; \
+     s@^max_execution_time.*@max_execution_time = 600@; \
+     s@^max_input_vars.*@max_input_vars = 1000@; \
+     s@^memory_limit.*@memory_limit = 512M@; \
+     s@^error_reporting.*@error_reporting = E_ALL@; \
+     s@^upload_max_filesize.*@upload_max_filesize = 20M@" \
+     /etc/php.ini 
+
+    if [ ! -f /etc/rc.d/init.d/php-fpm ];then
+        log_error "Not found ${php_src_dir}/sapi/fpm/init.d.php-fpm.in"
+        exit 1
+    fi 
+
+    sed -i "s@^prefix=.*@prefix=${php_install_dir}@; \
+            s/^exec_prefix=.*/exec_prefix=\${prefix}/; \
+            s/^php_fpm_BIN=.*/php_fpm_BIN=\${exec_prefix}\/sbin\/php-fpm/; \
+            s/^php_fpm_CONF=.*/php_fpm_CONF=\${prefix}\/etc\/php-fpm.conf/; \
+            s/^php_fpm_PID=.*/php_fpm_PID=\${prefix}\/var\/run\/php-fpm.pid/" \
+            /etc/rc.d/init.d/php-fpm 
+
+    if [[ "$?" -ne 0 ]];then
+        log_error "Configure php-fpm failure"
+        exit 1
+    fi 
+
+    chmod +x /etc/rc.d/init.d/php-fpm 
+
+    if [ -f /etc/profile.d/php.sh ];then
+        rm -f /etc/profile.d/php.sh 
+    fi
+
+    
+    # php-fpm config #
+    
+    /usr/bin/cp -f ${php_install_dir}/etc/php-fpm.conf.default ${php_fpm_conf_dir}
+
+    if [[ "$?" -ne 0 ]];then
+        log_error "Not found ${php_fpm_conf_dir}, copy php-fpm.conf failure" 
+        exit 1
+    fi 
+    
+    sed -i "s@^pm.max_children.*@pm.max_children = 50@; \
+            s@^pm.start_servers.*@pm.start_servers = 5@; \
+            s@^pm.min_spare_servers.*@pm.min_spare_servers = 2@; \
+            s@^pm.max_spare_servers.*@pm.max_spare_servers = 8@;" \
+            ${php_fpm_conf_dir}
+
+    sed -i "s@;pid = .*@pid = ${php_install_dir}/var/run/php-fpm.pid@" ${php_fpm_conf_dir}
+
+    #sed -i "s@^listen.*@listen = $(ifconfig eth0 | awk -F'[ :]+' '/inet addr/{print$4}'):9000@" ${PHP_INSTALL_DIR}/etc/php-fpm.conf 
+    sed -i "s@^listen.*@listen = 127.0.0.1:9000@" ${php_fpm_conf_dir} 
+    
+    if [[ "$?" -ne 0 ]];then
+        log_error  "Configure ${php_fpm_conf_dir} failure"
+        exit 1
+    fi
+
+    cat ${php_fpm_conf_dir} | grep -vE '^;|^[[:space:]]{0,}$'
+
+    echo ${php_fpm_conf_dir}
 }
 
 __COO_Init()
